apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
spec:
  selector:
    app: go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 5.10.48.0/20  # Vodafone West GmbH
  - 5.10.160.0/19 # Vodafone West GmbH